version: "3.8"

services:
  app:
    image: ghcr.io/cmelkebeek/next-cda241/next-app:dev
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
