on:
  push:
    branches:
      - main
      - develop

jobs:
  buildDocker:
    runs-on: ubuntu-latest

    # Utilisation d'un environnement GitHub selon la branche
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Définir le tag selon la branche
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build et push de l'image Docker
        run: |
          docker build -t ghcr.io/cmelkebeek/next-cda241/next-app:${TAG} .
          docker push ghcr.io/cmelkebeek/next-cda241/next-app:${TAG}

      - name: Mise à jour du container sur la machine distante
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/cmelkebeek/next-cda241/next-app:${TAG}
            docker stop next-cda241-app-1 || true
            docker rm next-cda241-app-1 || true
            docker run -d --name next-cda241-app-1 -p 80:3000 ghcr.io/cmelkebeek/next-cda241/next-app:${TAG}
