on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #      - name: Build and push Docker image
      #        run: |
      #          docker build -t ghcr.io/${{ github.repository }}/next-app:latest .
      #          docker push ghcr.io/${{ github.repository }}/next-app:latest

      - name: Build and push Docker image with docker action
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/next-app:${{ github.ref_name }}

  deploy-prod:
    needs: build-push
    environment:
      name: prod
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd prod
            sudo docker compose -f docker-compose.prod.yml pull
            sudo docker compose -f docker-compose.prod.yml up -d

  deploy-test:
    needs: build-push
    environment:
      name: test
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd test
            sudo docker compose -f docker-compose.test.yml pull
            sudo docker compose -f docker-compose.test.yml up -d
