on: [push]

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_ACTOR }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build et push de l'image Docker
        run: |
          docker build -t ghcr.io/cmelkebeek/next-cda241/next-app:latest .
          docker push ghcr.io/cmelkebeek/next-cda241/next-app:latest
