on: [push]

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_ACTOR }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build et push de l'image Docker
        run: |
          docker build -t ghcr.io/cmelkebeek/next-cda241/next-app:latest .
          docker push ghcr.io/cmelkebeek/next-cda241/next-app:latest

      - name: Update container in production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "docker pull ghcr.io/cmelkebeek/next-cda241/next-app:latest && \
            docker stop next-app || true && \
            docker rm next-app || true && \
            docker run -d --name next-app -p 80:3000 ghcr.io/cmelkebeek/next-cda241/next-app:latest"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH__KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
