on: [push]

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build et push de l'image Docker
        run: |
          docker build -t ghcr.io/cmelkebeek/next-cda241/next-app:latest .
          docker ghcr.io/cmelkebeek/next-cda241/next-app:latest
