name: Build Application

on:
  push:
    branches:
      - main # Déclencher l'action lorsque tu pousses sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Build du projet
        run: |
          echo "Building the project..."
          npm run build

  test:
    needs: build # Cette ligne indique que le job test dépend du job build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Test de l'application
        run: |
          echo "Testing the application..."
          npm run e2e:headless

      - name: Upload des vidéos de test
        if: always() # Exécute cette étape même si les tests échouent
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: cypress/videos/
          retention-days: 1 # Conserve les vidéos pendant 7 jours
