name: Build Application

on:
  push:
    branches:
      - main # Déclencher l'action lorsque tu pousses sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build du projet
        run: |
          echo "Building the project..."
          # Ajoute ici les commandes pour construire ton projet, par exemple :
          npm install
          npm run build
