name: Test Application

on:
  workflow_run:
    workflows: ["Build Application"] # Nom du workflow de build
    types:
      - completed
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Télécharger les artefacts du build
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: build-output # Nom de l'artefact à télécharger
          path: .next # Dossier où extraire les artefacts

      - name: Test de l'application
        run: |
          echo "Testing the application..."
          npm run e2e:headless

      - name: Upload des vidéos de test
        if: always() # Exécute cette étape même si les tests échouent
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: cypress/videos/
          retention-days: 7 # Conserve les vidéos pendant 7 jours
